//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIPySerwer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calls
    {
        public int ID_Calls { get; set; }
        public int From_ID { get; set; }
        public int To_ID { get; set; }
        public System.DateTime Date_Begin { get; set; }
        public System.DateTime Date_End { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
